defmodule Humanity.Decks.Default do
  def black_cards do
    [
      "______ + ______ = ______.",
      "______ is a slippery slope that leads to ______.",
      "______: good to the last drop.",
      "______: kid-tested, mother-approved.",
      "______: Once you pop, the fun don't stop!",
      "______? Jim'll fix it!",
      "______? There's an app for that.",
      "______. Betcha can't have just one!",
      "______. High five, bro.",
      "______. It's a trap!",
      "______. That was so metal.",
      "______. That's how I want to die.",
      "______. That's why mums go to Iceland.",
      "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ______.",
      "A romantic, candlelit dinner would be incomplete without ______.",
      "ABC presents: \"______: The Story of ______.\"",
      "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ______.",
      "After Hurricane Katrina, Sean Penn brought ______ to all the people of New Orleans.",
      "After the earthquake, Sean Penn brought ______ to the people of Haiti.",
      "Air Canada guidelines now prohibit ______ on airplanes.",
      "Airport security guidelines now prohibit ______ on airplanes.",
      "Alternative medicine is now embracing the curative powers of ______.",
      "And the Academy Award for ______ goes to ______.",
      "And the BAFTA for ______ goes to ______.",
      "Anthropologists have recently discovered a primitive tribe that worships ______.",
      "Are you thinking what I'm thinking, B1?   I think I am, B2: it's ______ time!",
      "As my New Year's resolution, I vow to give up ______.",
      "BILLY MAYS HERE FOR ______.",
      "But before I kill you, Mr. Bond, I must show you ______.",
      "Channel 4 presents ______, the story of ______.",
      "Channel 5's new reality show features eight washed-up celebrities living with ______.",
      "Channel 9 is pleased to present its new variety show, \"Hey Hey It's ______.\"",
      "Coming to Broadway this season, ______: The Musical.",
      "Coming to the West End this year, ______: The Musical.",
      "Crikey! I've never seen ______ like this before! Let's get a bit closer.",
      "CTV presents \"______: the Story of ______.\"",
      "Daddy, why is mommy crying?",
      "Daddy, why is mummy crying?",
      "Dear Abby, I'm having some trouble with ______ and would like your advice.",
      "Dear Agony Aunt, I'm having some trouble with ________ and I need your advice.",
      "Due to a PR fiasco, Walmart no longer offers ______.",
      "During his childhood, Salvador Dali produced hundreds of paintings of ______.",
      "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ______.",
      "During sex, I like to think about ______.",
      "For my next trick, I will pull ______ out of ______.",
      "Fun tip! When your man asks you to go down on him, try surprising him with ______ instead.",
      "Here is the church Here is the steeple Open the doors And there is ______.",
      "Hey Reddit! I'm ______. Ask me anything.",
      "How am I maintaining my relationship status?",
      "How did I lose my virginity?",
      "I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.",
      "I drink to forget ______.",
      "I get by with a little help from ______.",
      "I got 99 problems but ______ ain't one.",
      "I never truly understood ______ until I encountered ______.",
      "I wish I hadn't lost the instruction manual for ______.",
      "I'm going on a cleanse this week. Nothing but kale juice and ______.",
      "I'm sorry, Professor, but I couldn't complete my homework because of ______.",
      "I'm sorry, Sir, but I couldn't complete my homework because of ______.",
      "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
      "In 1,000 years, when paper money is but a distant memory, ______ will be our currency.",
      "In a world ravaged by ______, our only solace is ______.",
      "In an attempt to reach a wider audience, the National Museum of Australia has opened an interactive exhibit on ______.",
      "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ______.",
      "In Australia, ______ is twice as big and twice as deadly.",
      "In her latest feature-length film, Tracy Beaker struggles with ______ for the first time.",
      "In his new summer comedy, Rob Schneider is ______ trapped in the body of ______.",
      "In L.A. County Jail, word is you can trade 200 cigarettes for ______.",
      "In M. Night Shyamalan's new movie, Bruce Willis discovers that ______ had really been ______ all along.",
      "In Michael Jackson's final moments, he thought about ______.",
      "In the new Disney Channel Original Movie, Hannah Montana struggles with ______ for the first time.",
      "In Wormwood Scrubs, word is you can trade 200 cigarettes for ______.",
      "Instead of coal, Father Christmas now gives bad children ______.",
      "Instead of coal, Santa now gives the bad children ______.",
      "Introducing the amazing superhero/sidekick duo! It's ______ and ______!",
      "Introducing X-Treme Baseball! It's like baseball, but with ______!",
      "It’s a pity that kids these days are all getting involved with ______.",
      "Just saw this upsetting video! Please retweet!! #stop______",
      "Kids, I don't need drugs to get high. I'm high on ______.",
      "Life for Aboriginal people was forever changed when the white man introduced them to ______.",
      "Life for American Indians was forever changed when the White Man introduced them to ______.",
      "Life was difficult for cavemen before ______.",
      "Lifetime® presents \"______: the Story of ______.\"",
      "Major League Baseball has banned ______ for giving players an unfair advantage.",
      "Make a haiku.",
      "Maybe she's born with it. Maybe it's ______.",
      "MTV's new reality show features eight washed-up celebrities living with ______.",
      "Next from J.K. Rowling: Harry Potter and the Chamber of ______.",
      "Next on ESPN2: The World Series of ______.",
      "Next on Nine's Wide World of Sports: The World Championship of ______.",
      "Next on Sky Sports: The World Championship of ________.",
      "Next on TSN: The World Series of ______.",
      "Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ________.",
      "Now at the National Museum of Australia: an interactive exhibit on ______.",
      "Now at the Natural History Museum: an interactive exhibit on ______.",
      "Now at the Royal Ontario Museum: an interactive exhibit on ______.",
      "Now at the Smithsonian: an interactive exhibit on ______.",
      "O Canada, we stand on guard for ______.",
      "Oi! Show us ______!",
      "Qantas now prohibits ______ on airplanes.",
      "Rumor has it that Vladimir Putin's favorite dish is ______ stuffed with ______.",
      "Sorry everyone, I just ______.",
      "\"Step 1: ______.\nStep 2: ______.\nStep 3: Profit.\"",
      "Studies show that lab rats navigate mazes 50% faster after being exposed to ______.",
      "TFL apologizes for the delay in train service due to ______.",
      "That's right, I killed ______. How, you ask? ______.",
      "The class field trip was completely ruined by ______.",
      "The Natural History Museum has just opened an interactive exhibit on ________.",
      "The new Chevy Tahoe. With the power and space to take ______ everywhere you go.",
      "The school excursion was completely ruined by ______.",
      "The school field trip was completely ruined by ______.",
      "The school trip was completely ruined by ______.",
      "The Smithsonian Museum of Natural History has just opened an interactive exhibit on ______.",
      "The TFL apologizes for the delay in train service due to ________. ",
      "The theme for next year's Eurovision Song Contest is \"We are ________.\"",
      "The U.S. has begun airdropping ______ to the children of Afghanistan.",
      "They said we were crazy. They said we couldn't put ______ inside of ______. They were wrong.",
      "This is the way the world ends This is the way the world ends Not with a bang but with ______.",
      "Today on Jerry Springer: \"Help! My son is ______!\"",
      "Today on Maury: \"Help! My son is ______!\"",
      "Today on The Jeremy Kyle Show: \"Help! My son is ________!\"",
      "TSA guidelines now prohibit ______ on airplanes.",
      "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ______.",
      "War! What is it good for?",
      "Well if you'll excuse me, gentlemen, I have a date with ______.",
      "What am I giving up for Lent?",
      "What are my parents hiding from me?",
      "What are school administrators using to curb rampant teenage pregnancy?",
      "What broke up the original Wiggles?",
      "What did I bring back from Amsterdam?",
      "What did I bring back from Bali?",
      "What did I bring back from Mexico?",
      "What did the US airdrop to the children of Afghanistan?",
      "What did Vin Diesel eat for dinner?",
      "What do old people smell like?",
      "What does Dick Cheney prefer?",
      "What don't you want to find in your Chinese food?",
      "What don't you want to find in your Kung Pao chicken?",
      "What don't you want to find in your Mongolian beef?",
      "What ended my last relationship?",
      "What gets better with age?",
      "What gives me uncontrollable gas?",
      "What helps Barack Obama unwind?",
      "What helps Obama unwind?",
      "What is Batman's guilty pleasure?",
      "What is George W. Bush thinking about right now?",
      "What kept Margaret Thatcher busy in her waning years?",
      "What made my first kiss so awkward?",
      "What never fails to liven up the party?",
      "What will always get you laid?",
      "What will I bring back in time to convince people that I am a powerful wizard?",
      "What would grandma find disturbing, yet oddly charming?",
      "What's a girl's best friend?",
      "What's my anti-drug?",
      "What's my secret power?",
      "What's Teach for America using to inspire inner city students to succeed?",
      "What's that smell?",
      "What's that sound?",
      "What's the Canadian government using to inspire rural students to succeed?",
      "What's the crustiest?",
      "What's the most emo?",
      "What's the new fad diet?",
      "What's the next Happy Meal® toy?",
      "What's the next superhero?",
      "What's the next superhero/sidekick duo?",
      "What's there a ton of in heaven?",
      "What's there a tonne of in heaven?",
      "When I am a billionare, I shall erect a 20-metre statue to commemorate ______.",
      "When I am a billionare, I shall erect a 50-foot statue to commemorate ______.",
      "When I am President of the United States, I will create the Department of ______.",
      "When I am Prime Minister of Canada, I will create the Department of ______.",
      "When I am Prime Minister of the United Kingdom, I will create the Ministry of ______.",
      "When I am Prime Minister, I will create the Ministry of ______.",
      "When I was tripping on acid, ______ turned into ______.",
      "When I'm in prison, I'll have ______ smuggled in.",
      "When Pharaoh remained unmoved, Moses called down a Plague of ______.",
      "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ______.",
      "White people like ______.",
      "Who stole the cookies from the cookie jar?",
      "Why am I sticky?",
      "Why can't I sleep at night?",
      "Why do I hurt all over?"
    ]
  end

  def white_cards do
    [
      "(I am doing Kegels right now.)",
      "100% Pure New Zealand.",
      "2 Girls 1 Cup.",
      "400 years of colonial atrocities.",
      "50,000 volts straight to the nipples.",
      "72 virgins.",
      "8 oz. of sweet Mexican black-tar heroin.",
      "A bag of magic beans.",
      "A balanced breakfast.",
      "A ball of earwax, semen, and toenail clippings.",
      "A big hoopla about nothing.",
      "A bit of slap and tickle.",
      "A bitch slap.",
      "A bleached arsehole.",
      "A bleached asshole.",
      "A Bop It™.",
      "A brain tumor.",
      "A brain tumour.",
      "A bucket of fish heads.",
      "A can of whoop-ass.",
      "A caress of the inner thigh.",
      "A cartoon camel enjoying the smooth, refreshing taste of a cigarette.",
      "A Chelsea smile. ",
      "A clandestine butt scratch.",
      "A cooler full of organs.",
      "A cute, fuzzy koala, but it has chlamydia.",
      "A death ray.",
      "A decent fucking Internet connection.",
      "A defective condom.",
      "A despondent Maple Leafs fan sitting all alone.",
      "A didgeridildo.",
      "A disappointing birthday party.",
      "A drive-by shooting.",
      "A fair go.",
      "A falcon with a cap on its head.",
      "A fanny fart.",
      "A fetus.",
      "A five-litre goon bag.",
      "A Fleshlight.",
      "A foetus.",
      "A foul mouth.",
      "A gassy antelope.",
      "A gentle caress of the inner thigh.",
      "A ginger's freckled ballsack.",
      "A good sniff.",
      "A grande sugar-free iced soy caramel macchiato.",
      "A Gypsy curse.",
      "A homoerotic volleyball montage.",
      "A Japanese whaling operation.",
      "A hot mess.",
      "A LAN party.",
      "A lifetime of sadness.",
      "A literal tornado of fire.",
      "A live studio audience.",
      "A look-see.",
      "A mad cow.",
      "A madman who lives in a police box and kidnaps women.",
      "A man on the brink of orgasm.",
      "A mating display.",
      "A micropenis.",
      "A micropig wearing a tiny raincoat and booties.",
      "A middle-aged man on roller skates.",
      "A mime having a stroke.",
      "A moment of silence.",
      "A monkey smoking a cigar.",
      "A mopey zoo lion.",
      "A much younger woman.",
      "A murder most foul.",
      "A neglected Tamagotchi™.",
      "A nice cup of tea.",
      "A pangender octopus who roams the cosmos in search of love.",
      "A posh wank.",
      "A pyramid of severed heads.",
      "A really cool hat.",
      "A robust mongoloid.",
      "A sad handjob.",
      "A salty surprise.",
      "A sassy black woman.",
      "A sausage festival.",
      "A saxophone solo.",
      "A sea of troubles.",
      "A sick burnout.",
      "A sickly child-king.",
      "A six-point plan to stop the boats.",
      "A slab of VB and a pack of durries.",
      "A snapping turtle biting the tip of your penis.",
      "A sober Irishman who doesn't care for potatoes.",
      "A soggy Sao.",
      "A spastic nerd.",
      "A stingray barb through the chest.",
      "A stray pube.",
      "A subscription to Men's Fitness.",
      "A Super Soaker™ full of cat pee.",
      "A thermonuclear detonation.",
      "A thousand Scottish warriors lifting their kilts in unison.",
      "A Tim Hortons franchise.",
      "A time travel paradox.",
      "A tiny horse.",
      "A tribe of warrior women.",
      "A vajazzled vagina.",
      "A vindaloo poo.",
      "A wheelchair death race.",
      "A white van man.",
      "A windmill full of corpses.",
      "A wisecracking terrorist.",
      "A zesty breakfast burrito.",
      "Aaron Burr.",
      "Abstinence.",
      "Accidentally slipping yourself a roofie.",
      "Active listening.",
      "Actually taking candy from a baby.",
      "Adderall™.",
      "Adult Friendfinder.",
      "Advice from a wise, old black man.",
      "African children.",
      "Agriculture.",
      "AIDS.",
      "Alcohol poisoning.",
      "Alcoholism.",
      "All four prongs of an echidna's penis.",
      "All-you-can-eat shrimp for $4.99.",
      "All-you-can-eat shrimp for $8.99.",
      "Altar boys.",
      "America.",
      "American Gladiators.",
      "Americanization.",
      "Amputees.",
      "An AK-47 assault rifle.",
      "An AR-15 assault rifle.",
      "An argument with Richard Dawkins.",
      "An asymmetric boob job.",
      "An endless stream of diarrhea.",
      "An endless stream of diarrhoea.",
      "An entrenched class system.",
      "An erection that lasts longer than four hours.",
      "An honest cop with nothing left to lose.",
      "An icepick lobotomy.",
      "An icy handjob from an Edmonton hooker.",
      "An M. Night Shyamalan plot twist.",
      "An M16 assault rifle.",
      "An Oedipus complex.",
      "An oversized lollipop.",
      "An ugly face.",
      "An uppercut.",
      "Anal beads.",
      "Another goddamn vampire movie.",
      "Anything that comes out of Prince Philip's mouth.",
      "Apologizing.",
      "Arnold Schwarzenegger.",
      "Asians who aren't good at math.",
      "Assless chaps.",
      "Attitude.",
      "Auschwitz.",
      "Australia.",
      "Authentic Mexican cuisine.",
      "Autocannibalism.",
      "AXE Body Spray.",
      "Badger culling.",
      "Ball-by-ball commentary from Richie Benaud.",
      "Balls.",
      "Bananas in Pajamas.",
      "Barack Obama.",
      "BATMAN!!!",
      "Battlefield amputations.",
      "Becoming a blueberry.",
      "Bees?",
      "Being a dick to children.",
      "Being a motherfucking sorcerer.",
      "Being Canadian.",
      "Being fabulous.",
      "Being fat and stupid.",
      "Being hunted like a fox.",
      "Being marginalised.",
      "Being marginalized.",
      "Being on fire.",
      "Being rich.",
      "Bestiality.",
      "Bill Nye the Science Guy.",
      "Bingeing and purging.",
      "Bio-engineered assault turtles with acid breath.",
      "Bitches.",
      "Black people.",
      "Bling.",
      "Blood, toil, tears, and sweat.",
      "Blowing up Parliament.",
      "Boat people; half boat, half human.",
      "Bogies.",
      "Bond, James Bond.",
      "Bono.",
      "Booby-trapping the house to foil burglars.",
      "Boogers.",
      "Breaking out into song and dance.",
      "Britney Spears at 55.",
      "Brown people.",
      "Buckfast Tonic Wine.",
      "Burning down the White House.",
      "Canada: America's Hat.",
      "Canned tuna with extra dolphin.",
      "Capturing Newt Gingrich and forcing him to dance in a monkey suit.",
      "Cards Against Humanity.",
      "Cashed-up bogans.",
      "Catapults.",
      "Centaurs.",
      "Chainsaws for hands.",
      "Charisma.",
      "Cheating in the Paralympics.",
      "Cheating in the Special Olympics.",
      "Cheeky bum sex.",
      "Child abuse.",
      "Child beauty pageants.",
      "Children on leashes.",
      "Chivalry.",
      "Christopher Walken.",
      "Chunks of dead backpacker.",
      "Chunks of dead hitchhiker.",
      "Chunks of dead prostitute.",
      "Chutzpah.",
      "Civilian casualties.",
      "Classist undertones.",
      "Clive Palmer's soft, shitty body.",
      "Coat hanger abortions.",
      "Cockfights.",
      "College.",
      "Completely unwarranted confidence.",
      "Concealing a boner.",
      "Concealing an erection.",
      "Consensual sex.",
      "Consultants.",
      "Contagious face cancer.",
      "Cookie Monster devouring the Eucharist wafers.",
      "Copping a feel.",
      "Cottaging.",
      "Count Chocula.",
      "Court-ordered rehab.",
      "Creed.",
      "Crippling debt.",
      "Crucifixion.",
      "Crumbs all over the bloody carpet.",
      "Crumbs all over the god damn carpet.",
      "Crumpets with the Queen.",
      "Crystal meth.",
      "Cuddling.",
      "Customer service representatives.",
      "Cybernetic enhancements.",
      "Daddies® Brown Sauce.",
      "Daddy issues.",
      "Daniel Radcliffe's delicious arsehole.",
      "Daniel Radcliffe's delicious asshole.",
      "Danny DeVito.",
      "Dark and mysterious forces beyond our control.",
      "Darth Vader.",
      "Date rape.",
      "Dave Matthews Band.",
      "David Bowie flying in on a tiger made of lightning.",
      "David Cameron.",
      "Dead babies.",
      "Dead parents.",
      "Dental dams.",
      "Destroying the evidence.",
      "Dick Cheney.",
      "Dick fingers.",
      "Dirty nappies.",
      "Dogging.",
      "Doin' it in the butt.",
      "Doin' it up the bum.",
      "Doing a shit in Pudsey Bear's eyehole.",
      "Doing crimes.",
      "Doing the right thing.",
      "Domino's™ Oreo™ Dessert Pizza.",
      "Don Cherry's wardrobe.",
      "Donald Trump.",
      "Douchebags on their iPhones.",
      "Dr. Martin Luther King, Jr.",
      "Drinking alone.",
      "Drinking out of the toilet and eating garbage.",
      "Drinking out of the toilet and eating rubbish.",
      "Dropping a baby down the dunny.",
      "Dropping a chandelier on your enemies and riding the rope up.",
      "Drowning the kids in the bathtub.",
      "Druids.",
      "Drum circles.",
      "Dry heaving.",
      "Dwarf tossing.",
      "Dying of dysentery.",
      "Dying.",
      "Eastern European Turbo-Folk music.",
      "Eating all of the cookies before the AIDS bake-sale.",
      "Eating the last known bison.",
      "Eating too much of a lamp.",
      "Ecstasy.",
      "Ed Balls.",
      "Edible underpants.",
      "Edible underwear.",
      "Egging an MP.",
      "Elderly Japanese men.",
      "Electricity.",
      "Embryonic stem cells.",
      "Emma Watson.",
      "Emotions.",
      "England.",
      "Erectile dysfunction.",
      "Establishing dominance.",
      "Estrogen.",
      "Ethnic cleansing.",
      "Eugenics.",
      "Euphoria™ by Calvin Klein.",
      "Exactly what you'd expect.",
      "Excalibur.",
      "Exchanging pleasantries.",
      "Existentialists.",
      "Expecting a burp and vomiting on the floor.",
      "Explosions.",
      "Extremely tight pants.",
      "Extremely tight trousers.",
      "Fading away into nothingness.",
      "Faffing about.",
      "Faith healing.",
      "FALCON PUNCH!!!",
      "Famine.",
      "Fancy Feast®.",
      "Farting and walking away.",
      "Farting into your petticoats and wafting it at Lord Gregory.",
      "Fear itself.",
      "Feeding Rosie O'Donnell.",
      "Fiery poops.",
      "Fiery poos.",
      "Figgy pudding.",
      "Filling Sean Hannity with helium and watching him float away.",
      "Finger painting.",
      "Fingering.",
      "Firing a rifle into the air while balls deep in a squealing hog.",
      "Five litres of Special Brew.",
      "Five-Dollar Footlongs™.",
      "Flash flooding.",
      "Flavored condoms.",
      "Flesh-eating bacteria.",
      "Flightless birds.",
      "Flying sex snakes.",
      "Foreskin.",
      "Forgetting the Alamo.",
      "Former President George W. Bush.",
      "Four Loko.",
      "Free samples.",
      "Friction.",
      "Friendly fire.",
      "Friends who eat all the snacks.",
      "Friends with benefits.",
      "Frolicking.",
      "Front butt.",
      "Full frontal nudity.",
      "Funky fresh rhymes.",
      "Gandhi.",
      "Garth Brooks.",
      "Gary Coleman.",
      "Gary Glitter.",
      "Geese.",
      "Genghis Khan.",
      "Genital piercings.",
      "Gentleman's Relish®.",
      "Genuine human connection.",
      "German dungeon porn.",
      "Germans on holiday.",
      "Getting crushed by a vending machine.",
      "Getting drunk on mouthwash.",
      "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.",
      "Getting married, having a few kids, buying some stuff, retiring to Queensland, and dying.",
      "Getting naked and watching /Play School/.",
      "Getting naked and watching CBeebies.",
      "Getting naked and watching Nickelodeon.",
      "Getting pregnant again.",
      "Getting really high.",
      "Getting so angry that you pop a boner.",
      "Getting so angry that you pop a stiffy.",
      "Getting wed, having a few kids, taking some pictures, retiring to the south of France, and dying.",
      "Ghosts.",
      "Girls who shouldn't go wild.",
      "Giving 110%.",
      "Giving birth to the Antichrist.",
      "Glassing a wanker.",
      "Glenn Beck being harried by a swarm of buzzards.",
      "Glenn Beck catching his scrotum on a curtain hook.",
      "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.",
      "Glenn Beck.",
      "Global warming.",
      "Gloryholes.",
      "Goats eating cans.",
      "Goats eating coins.",
      "Goblins.",
      "God.",
      "GoGurt®.",
      "Golden showers.",
      "Good-natured, fun-loving Aussie racism.",
      "Grandma.",
      "Grave robbing.",
      "Growing a pair.",
      "Guys who don't call.",
      "Haggis.",
      "Half a kilo of pure China White heroin.",
      "Half-assed foreplay.",
      "Harry Potter erotica.",
      "Have some more kugel.",
      "Having a Golden Gaytime.",
      "Having a shag in the back of a ute.",
      "Having anuses for eyes.",
      "Having big dreams but no realistic way to achieve them.",
      "Having sex with every man in Winnipeg.",
      "Heartwarming orphans.",
      "Heath Ledger.",
      "Helplessly giggling at the mention of Hutus and Tutsis.",
      "Her Majesty, Queen Elizabeth II.",
      "Her Royal Highness, Queen Elizabeth II.",
      "Heritage minutes.",
      "Heritage minutes.",
      "Heteronormativity.",
      "Hip hop jewels.",
      "Historically black colleges.",
      "Holding down a child and farting all over him.",
      "Home video of Oprah sobbing into a Lean Cuisine®.",
      "Homeless people.",
      "Homo milk.",
      "Hope.",
      "Hormone injections.",
      "Horrifying laser hair removal accidents.",
      "Horse meat.",
      "Hospice care.",
      "Hot cheese.",
      "Hot people.",
      "Hot Pockets®.",
      "However much weed $20 can buy.",
      "However much weed £20 can buy.",
      "Hulk Hogan.",
      "Hunting \"accidents\".",
      "Hurling one's body down a hill in pursuit of a wheel of cheese.",
      "Hurricane Katrina.",
      "Ice.",
      "I'm friends with your dad on Facebook.",
      "Impotence.",
      "Improvised explosive devices.",
      "Inappropriate yelling.",
      "Inappropriate yodeling.",
      "Incest.",
      "Inserting a jam jar into my anus.",
      "Inserting a Mason jar into my anus.",
      "Intelligent design.",
      "Invading Poland.",
      "Irritable Bowel Syndrome.",
      "Italians.",
      "Jade Goody's cancerous remains.",
      "Jedward.",
      "Jehovah's Witnesses.",
      "Jennifer Lawrence.",
      "Jerking off into a pool of children's tears.",
      "Jew-fros.",
      "Jewish fraternities.",
      "Jibber-jabber.",
      "Jimmy Savile.",
      "Jobs.",
      "Joe Biden.",
      "John Howard's eyebrows.",
      "John Wilkes Booth.",
      "Judge Judy.",
      "Just touching David Beckham's hair.",
      "Justin Bieber.",
      "Kamikaze pilots.",
      "Kanye West.",
      "Keanu Reeves.",
      "Keeping Christ in Christmas.",
      "Keg stands.",
      "Kibbles n' Bits.",
      "Kids with ass cancer.",
      "Kids with bum cancer.",
      "Kim Jong-il.",
      "Lactation.",
      "Lady Gaga.",
      "Lance Armstrong's missing testicle.",
      "Land mines.",
      "Laying an egg.",
      "Leaked footage of Kate Middleton's colonoscopy.",
      "Leaving an awkward voicemail.",
      "Leprosy.",
      "Letting yourself go.",
      "Liberals.",
      "Licking things to claim them as your own.",
      "Lockjaw.",
      "Loose lips.",
      "Lumberjack fantasies.",
      "Lunchables™.",
      "LYNX® Body Spray.",
      "Mad cow disease.",
      "Madeleine McCann.",
      "Magnets.",
      "Making a pouty face.",
      "Making sex at her.",
      "Making up for centuries of oppression with one day of apologising.",
      "Man meat.",
      "Marky Mark and the Funky Bunch.",
      "Martha Stewart.",
      "Massive, widespread drought.",
      "Masturbation.",
      "Mathletes.",
      "Maureen of Blackpool, Reader's Wife of the Year 1988.",
      "Me time.",
      "MechaHitler.",
      "Men.",
      "Menstrual rage.",
      "Menstruation.",
      "Michael Jackson.",
      "Michelle Obama's arms.",
      "Miley Cyrus at 55.",
      "Millions of cane toads.",
      "Millwall fans.",
      "Mining accidents.",
      "Mistaking a retarded person for someone who's merely deaf.",
      "Morgan Freeman's voice.",
      "Mountain Dew Code Red.",
      "Mouth herpes.",
      "Mr. Clean, right behind you.",
      "Mr. Dressup.",
      "Mr. Dressup.",
      "Mr. Snuffleupagus.",
      "Mr. Squiggle, the Man from the Moon.",
      "Muhammad (Peace Be Upon Him).",
      "Muhammad (Praise Be Unto Him).",
      "Multiple stab wounds.",
      "Mutually assured destruction.",
      "Mutually-assured destruction.",
      "Muzzy.",
      "My balls on your face.",
      "My black ass.",
      "My collection of high-tech sex toys.",
      "My ex-wife.",
      "My genitals.",
      "My humps.",
      "My inner demons.",
      "My relationship status.",
      "My sex life.",
      "My soul.",
      "My vagina.",
      "Naked News.",
      "Natalie Portman.",
      "Natural male enhancement.",
      "Natural selection.",
      "Nazis.",
      "Necrophilia.",
      "New Age music.",
      "Newfies.",
      "Newfies.",
      "Nickelback.",
      "Nicolas Cage.",
      "Nip slips.",
      "Nippers.",
      "Nipple blades.",
      "Nocturnal emissions.",
      "Not giving a shit about the Third World.",
      "Not reciprocating oral sex.",
      "Not wearing pants.",
      "Not wearing trousers.",
      "Nothing but sand.",
      "Obesity.",
      "Object permanence.",
      "Oestrogen.",
      "Old-people smell.",
      "One Direction's supple, hairless bodies.",
      "One trillion dollars.",
      "Oompa-Loompas.",
      "Opposable thumbs.",
      "Our first chimpanzee President.",
      "Overcompensation.",
      "Oversized lollipops.",
      "Pabst Blue Ribbon.",
      "Pac-Man uncontrollably guzzling cum.",
      "Paedophiles.",
      "Panda sex.",
      "Paris Hilton.",
      "Parting the Red Sea.",
      "Party poopers.",
      "Passable transvestites.",
      "Passing a kidney stone.",
      "Passive-aggression.",
      "Passive-aggressive Post-it notes.",
      "PCP.",
      "Peanut Butter Jelly Time.",
      "Pedophiles.",
      "Peeing a little bit.",
      "Penis breath.",
      "Penis envy.",
      "People who smell their own socks.",
      "Perfunctory foreplay.",
      "Permanent Orgasm-Face Disorder.",
      "Picking up girls at the abortion clinic.",
      "Pictures of boobs.",
      "Pixelated bukkake.",
      "Playing silly buggers.",
      "Police Brutality.",
      "Pooping back and forth. Forever.",
      "Pooping in a laptop and closing it.",
      "Pooping in the soup.",
      "Poopy diapers.",
      "Poor life choices.",
      "Poor people.",
      "Poorly-timed Holocaust jokes.",
      "Popped collars.",
      "Porn stars.",
      "Poutine.",
      "Poverty.",
      "Powerful thighs.",
      "Prancing.",
      "Praying the gay away.",
      "Preteens.",
      "Pretending to care.",
      "Profound respect and appreciation for indigenous culture.",
      "Pronouncing the names of northern Welsh towns.",
      "Prosti-tots.",
      "Pterodactyl eggs.",
      "Puberty.",
      "Public ridicule.",
      "Pulling out.",
      "Punching a congressman in the face.",
      "Punching an MP in the face.",
      "Puppies!",
      "Pussy Galore.",
      "Queefing.",
      "Queen Elizabeth's immaculate anus.",
      "Racially-biased SAT questions.",
      "Racism.",
      "Rap music.",
      "Raping and pillaging.",
      "Raptor attacks.",
      "Re-gifting.",
      "Rehab.",
      "Repression.",
      "Republicans.",
      "Riding off into the sunset.",
      "Ring Pops™.",
      "Rip Torn dropkicking anti-Semitic lesbians.",
      "Ripping off the Beatles.",
      "Road head.",
      "Rob Ford.",
      "Robbing a sperm bank.",
      "Robert Downey Jr.",
      "Robert Downey, Jr.",
      "RoboCop.",
      "Rohypnol.",
      "Ronald Reagan.",
      "Roofies.",
      "Rubbing Boris Johnson's belly until he falls asleep.",
      "Running out of semen.",
      "Rupert Murdoch.",
      "Rush Limbaugh's soft, shitty body.",
      "Same-sex ice dancing.",
      "Sarah Palin.",
      "Saxophone solos.",
      "Saying \"I love you.\"",
      "Scalping the Milkybar Kid.",
      "Scalping.",
      "Schmirler the Curler.",
      "Science.",
      "Scientology.",
      "Scousers.",
      "Scrubbing under the folds.",
      "Sean Connery.",
      "Sean Penn.",
      "Seduction.",
      "Seeing Grandma naked.",
      "Seeing Granny naked.",
      "Seething with quiet resentment.",
      "Self-loathing.",
      "Selling crack to children.",
      "Selling ice to children.",
      "Seppuku.",
      "Serfdom.",
      "Sex with Patrick Stewart.",
      "Sexting.",
      "Sexual peeing.",
      "Sexual tension.",
      "Sexy pillow fights.",
      "Shapeshifters.",
      "Shaquille O'Neal's acting career.",
      "Sharing needles.",
      "Shiny objects.",
      "Shipping convicts to Australia.",
      "Shitting out a perfect Cumberland sausage.",
      "Shorties and blunts.",
      "Showing up to an orgy for the food.",
      "Silence.",
      "Sipping artificial popcorn butter.",
      "Skeletor.",
      "Skippy the Bush Kangaroo.",
      "Slapping a biscuit out of an orphan's mouth.",
      "Smallpox blankets.",
      "Smegma.",
      "Sniffing glue.",
      "Snotsicles.",
      "Sobbing into a Hungry-Man™ Frozen Dinner.",
      "Soiling oneself.",
      "Solving problems with violence.",
      "Some bloody peace and quiet.",
      "Some god damn peace and quiet.",
      "Sorry, this content cannot be viewed in your region.",
      "Soup that is too hot.",
      "Spaniards.",
      "Spectacular abs.",
      "Sperm whales.",
      "Spontaneous human combustion.",
      "Stalin.",
      "Stephen Harper.",
      "Stephen Harper.",
      "Stephen Hawking talking dirty.",
      "Steve Irwin.",
      "Stifling a giggle at the mention of Hutus and Tutsis.",
      "Still being a virgin.",
      "Stormtroopers.",
      "Stranger danger.",
      "Strong female characters.",
      "Stunt doubles.",
      "Substitute teachers.",
      "Sucking some dicks to not get drafted.",
      "Summoning Harold Holt from the sea in a time of great need.",
      "Sunshine and rainbows.",
      "Surprise sex!",
      "Swag.",
      "Sweet, sweet vengeance.",
      "Switching to Geico®.",
      "Swooping.",
      "Synergistic management solutions.",
      "Syrupy sex with a maple tree.",
      "Take-backsies.",
      "Taking a sheep-wife.",
      "Taking off your shirt.",
      "Tangled Slinkys.",
      "Tap dancing like there's no tomorrow.",
      "Tasteful sideboob.",
      "Teaching a robot to love.",
      "Team-building exercises.",
      "Teenage pregnancy.",
      "Tentacle porn.",
      "Terry Fox's prosthetic leg.",
      "Testicular torsion.",
      "That one gay Teletubby.",
      "That thing that electrocutes your abs.",
      "The American Dream.",
      "The Amish.",
      "The art of seduction.",
      "The Big Bang.",
      "The big fucking hole in the ozone layer.",
      "The Black Death.",
      "The Blood of Christ.",
      "The bloody Welsh.",
      "The BNP.",
      "The Boy Scouts of America.",
      "The bush.",
      "The Care Bear Stare.",
      "The Chinese gymnastics team.",
      "The chronic.",
      "The clitoris.",
      "The cool, refreshing taste of Coca-Cola®.",
      "The cool, refreshing taste of Pepsi.",
      "The cool, refreshing taste of Pepsi®.",
      "The Dance of the Sugar Plum Fairy.",
      "The deformed.",
      "The Devil Himself.",
      "The Donald Trump Seal of Approval.™",
      "The drama club.",
      "The end of days.",
      "The entire cast of Downton Abbey.",
      "The entire Mormon Tabernacle Choir.",
      "The female orgasm.",
      "The FLQ.",
      "The folly of man.",
      "The forbidden fruit.",
      "The Force.",
      "The French.",
      "The gays.",
      "The glass ceiling.",
      "The Great Depression.",
      "The Great Emu War.",
      "The Hamburglar.",
      "The hardworking Mexican.",
      "The heart of a child.",
      "The Hillsborough Disaster.",
      "The Holy Bible.",
      "The homosexual agenda.",
      "The homosexual lifestyle.",
      "The Honey Monster.",
      "The Hustle.",
      "The inevitable heat death of the universe.",
      "The invisible hand.",
      "The Jews.",
      "The KKK.",
      "The Kool-Aid Man.",
      "The light of a billion suns.",
      "The Little Engine That Could.",
      "The Make-A-Wish® Foundation.",
      "The milk man.",
      "The milkman.",
      "The miracle of childbirth.",
      "The morbidly obese.",
      "The North.",
      "The Official Languages Act. La Loi sur les langues officielles.",
      "The Patriarchy.",
      "The penny whistle solo from \"My Heart Will Go On.\"",
      "The People's Elbow.",
      "The petty troubles of the landed gentry.",
      "The pirate's life.",
      "The placenta.",
      "The plot of a Michael Bay movie.",
      "The Pope.",
      "The profoundly handicapped.",
      "The Rapture.",
      "The Red Menace.",
      "The Rev. Dr. Martin Luther King, Jr.",
      "The rhythms of Africa.",
      "The Royal Canadian Mounted Police.",
      "The Scouts.",
      "The screams...the terrible screams.",
      "The South.",
      "The Stig.",
      "The sudden appearance of the Go Compare man.",
      "The Superdome.",
      "The taint; the grundle; the fleshy fun-bridge.",
      "The Tempur-Pedic® Swedish Sleep System™.",
      "The terrorists.",
      "The Thong Song.",
      "The Three-Fifths compromise.",
      "The token minority.",
      "The Trail of Tears.",
      "The true meaning of Christmas.",
      "The Übermensch.",
      "The Underground Railroad.",
      "The unstoppable tide of Islam.",
      "The violation of our most basic human rights.",
      "The Virginia Tech Massacre.",
      "The way James Bond treats women.",
      "The White Australia Policy.",
      "The wonders of the Orient.",
      "The World of Warcraft.",
      "The wrath of Vladimir Putin.",
      "Third base.",
      "This answer is postmodern.",
      "This year's mass shooting.",
      "Those times when you get sand in your vagina.",
      "Three dicks at the same time.",
      "Throwing a virgin into a volcano.",
      "Tickle Me Elmo.",
      "Tickling Sean Hannity, even after he tells you to stop.",
      "Tiger Woods.",
      "Tom Cruise.",
      "Toni Morrison's vagina.",
      "Tony Abbott in budgie smugglers.",
      "Too much hair gel.",
      "Tories.",
      "Total control of the media.",
      "Touching a pug right on his penis.",
      "Trench foot.",
      "Tweeting.",
      "Twinkies®.",
      "Twenty tonnes of bat shit.",
      "Two midgets shitting into a bucket.",
      "Unfathomable stupidity.",
      "Uppercuts.",
      "Used knickers.",
      "Used panties.",
      "Vegemite™.",
      "Vehicular homicide.",
      "Vehicular manslaughter.",
      "Viagra®.",
      "Vigilante justice.",
      "Vigorous jazz hands.",
      "Vikings.",
      "Vomiting into a kangaroo's pouch.",
      "Waiting till marriage.",
      "Waking up half-naked in a Denny's parking lot.",
      "Waking up half-naked in a Little Chef car park.",
      "Waking up half-naked in a Macca's car park.",
      "Wanking into a pool of children's tears.",
      "Waterboarding.",
      "Wearing underwear inside-out to avoid doing laundry.",
      "Wet dreams.",
      "When you fart and a little bit comes out.",
      "Whipping it out.",
      "Whiskas® Catmilk.",
      "White people.",
      "White privilege.",
      "White-man scalps.",
      "Wifely duties.",
      "Will Smith.",
      "William Shatner.",
      "Winking at old people.",
      "Wiping her bum.",
      "Wiping her butt.",
      "Women in yoghurt adverts.",
      "Women in yoghurt commercials.",
      "Women in yogurt commercials.",
      "Women's suffrage.",
      "Women's undies.",
      "World peace.",
      "Xenophobia.",
      "Yeast.",
      "YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
      "Your weird brother."
    ]
  end
end
